### ISSUE TITLE
Add CORS headers

### ISSUE THREAD

**Issue by ezheidtmann** [KnockSoftware/skugr#1]
At a minimum, all GET responses should include these headers:

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET 
```

**Comment by quicklywilliam** [comment]
https://docs.vapor.codes/2.0/http/cors/

**Comment by quicklywilliam** [comment]
Deployed, verified using https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fskugr-skugr.vapor.cloud%2Ffree_bikes&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote
